
import React, { useEffect } from 'react';
import { Button, Card, SectionTitle } from '../components/UI';
import { SEO } from '../components/SEO';

interface HomeProps {
  onNavigate: (view: string) => void;
}

export const Home: React.FC<HomeProps> = ({ onNavigate }) => {
  
  const tools = [
    {
      title: 'Competitor Analysis',
      desc: 'Ethically spy on top channels. Extract content gaps, weakness analysis, and strategic action plans using advanced AI scraping.',
      icon: '🕵️',
      id: 'competitors',
      color: 'from-purple-500 to-indigo-600',
      stat: 'Gap Analysis'
    },
    {
      title: 'Keyword Finder',
      desc: 'The 10-Point Logic System analyzes volume, difficulty, trends, and CPC to uncover low-competition, high-reward gems.',
      icon: '🔑',
      id: 'keywords',
      color: 'from-blue-500 to-cyan-500',
      stat: 'High Volume'
    },
    {
      title: 'Thumbnail Generator',
      desc: 'Generate CTR-optimized 4K thumbnails. AI automatically rewrites your prompt to follow visual psychology rules.',
      icon: '🎨',
      id: 'thumbnail-gen',
      color: 'from-pink-500 to-rose-500',
      stat: '4K Quality'
    },
    {
      title: 'Script Writer',
      desc: 'Stop staring at a blank page. Generate scripts with Hooks, Retention Spikes, and Visual Cues pre-formatted.',
      icon: '✍️',
      id: 'script',
      color: 'from-amber-500 to-orange-500',
      stat: 'Retention Optimized'
    },
    {
      title: 'Thumbnail Compare',
      desc: 'A/B Test before you publish. Our AI simulates human eye-tracking and emotional response to pick the winner.',
      icon: '🆚',
      id: 'compare',
      color: 'from-emerald-500 to-green-600',
      stat: 'A/B Testing'
    },
    {
      title: 'Title & Best Time',
      desc: 'Maximize reach with SEO titles and a predictive algorithm that tells you exactly when to hit publish.',
      icon: '⏰',
      id: 'title-time',
      color: 'from-slate-500 to-slate-700',
      stat: 'Algorithm Hacks'
    }
  ];

  const faqs = [
    {
      q: "How is TubeMaster different from other tools?",
      a: "TubeMaster uses a specialized '10-Point Logic' system for every analysis. We don't just give you data; we give you psychological context, retention strategies, and visual engineering advice derived from analyzing top creators."
    },
    {
      q: "Can I use the generated thumbnails commercially?",
      a: "Yes. All images generated by our AI are royalty-free and cleared for commercial use on YouTube, social media, and advertising campaigns."
    },
    {
      q: "Does the Script Writer work for any niche?",
      a: "Absolutely. Whether you are in Tech, Gaming, Beauty, or Education, our underlying model adapts the tone while maintaining the high-retention structural elements (Hooks, Stakes, Payoffs)."
    },
    {
      q: "Is the competitor analysis data accurate?",
      a: "We use real-time web grounding to fetch the latest public data from channels. The 'Strengths & Weaknesses' are derived from actual content performance and audience sentiment analysis."
    }
  ];

  const scrollToTools = () => {
    const toolsSection = document.getElementById('tools');
    if (toolsSection) {
      toolsSection.scrollIntoView({ behavior: 'smooth' });
    }
  };

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="space-y-24 pb-20">
      <SEO 
        title="YouTube Growth Suite" 
        description="The ultimate AI-powered toolkit for YouTube Creators. Competitor analysis, SEO keywords, thumbnail generation, and script writing."
        path="/"
      />
      
      {/* Hero Section */}
      <section className="relative min-h-[600px] flex items-center justify-center pt-10">
        {/* Abstract Background Mesh */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[1000px] h-[600px] bg-brand-600/20 blur-[120px] rounded-full -z-10 opacity-50 animate-pulse" style={{ animationDuration: '5s' }}></div>
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-purple-600/10 blur-[100px] rounded-full -z-10"></div>
        
        <div className="text-center max-w-4xl mx-auto space-y-8 px-4">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-900/50 border border-brand-500/30 backdrop-blur-md mb-4 animate-fade-in">
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-brand-500"></span>
            </span>
            <span className="text-sm font-medium text-brand-300 tracking-wide">AI Model Updated: Gemini 2.5 Flash</span>
          </div>
          
          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-white leading-[1.1] animate-fade-in" style={{ animationDelay: '100ms' }}>
            Scientific Growth for <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-300 via-brand-400 to-purple-400">Serious Creators</span>
          </h1>
          
          <p className="text-xl md:text-2xl text-slate-400 max-w-2xl mx-auto leading-relaxed animate-fade-in" style={{ animationDelay: '200ms' }}>
            Stop guessing. Start engineering. The only toolkit that combines generative AI with 
            <span className="text-slate-200 font-semibold"> viewer psychology</span> to explode your metrics.
          </p>
          
          <div className="flex flex-col sm:flex-row justify-center gap-4 pt-4 animate-fade-in" style={{ animationDelay: '300ms' }}>
            <Button 
              variant="glow" 
              className="w-full sm:w-auto px-8 py-4 text-lg"
              onClick={() => onNavigate('keywords')}
            >
              Start Growing Now 🚀
            </Button>
            <Button onClick={scrollToTools} variant="outline" className="w-full sm:w-auto px-8 py-4 text-lg border-slate-600 hover:border-white">
              View All Tools
            </Button>
          </div>

          {/* Social Proof / Stats */}
          <div className="grid grid-cols-3 gap-8 pt-12 border-t border-slate-800/50 mt-12 max-w-2xl mx-auto animate-fade-in" style={{ animationDelay: '500ms' }}>
             <div>
               <div className="text-3xl font-bold text-white">10+</div>
               <div className="text-xs uppercase tracking-widest text-slate-500 font-semibold">Logic Models</div>
             </div>
             <div>
               <div className="text-3xl font-bold text-white">4K</div>
               <div className="text-xs uppercase tracking-widest text-slate-500 font-semibold">Image Gen</div>
             </div>
             <div>
               <div className="text-3xl font-bold text-white">24/7</div>
               <div className="text-xs uppercase tracking-widest text-slate-500 font-semibold">Availability</div>
             </div>
          </div>
        </div>
      </section>

      {/* Tools Grid */}
      <section id="tools" className="scroll-mt-24">
        <SectionTitle 
          title="Your Growth Arsenal" 
          subtitle="A complete suite of specialized AI agents designed to handle every aspect of YouTube production, from ideation to publication."
          center
        />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {tools.map((tool) => (
            <div 
              key={tool.id} 
              onClick={() => onNavigate(tool.id)}
              className="group block h-full cursor-pointer"
            >
              <div className="h-full bg-slate-900/60 border border-slate-800 rounded-3xl p-8 hover:border-brand-500/50 transition-all duration-300 hover:bg-slate-800/80 hover:-translate-y-2 hover:shadow-2xl hover:shadow-brand-900/20 relative overflow-hidden backdrop-blur-sm">
                {/* Gradient Header Line */}
                <div className={`absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r ${tool.color}`} />
                <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-bl from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-bl-full pointer-events-none"></div>
                
                <div className="flex justify-between items-start mb-6">
                  <div className="text-5xl drop-shadow-lg filter grayscale group-hover:grayscale-0 transition-all duration-300 scale-100 group-hover:scale-110">{tool.icon}</div>
                  <span className="text-[10px] font-bold uppercase tracking-wider bg-slate-950 border border-slate-800 text-slate-400 px-2 py-1 rounded-md group-hover:text-brand-300 group-hover:border-brand-500/30 transition-colors">
                    {tool.stat}
                  </span>
                </div>
                
                <h3 className="text-2xl font-bold text-white mb-3 group-hover:text-brand-200 transition-colors">{tool.title}</h3>
                <p className="text-slate-400 leading-relaxed text-sm font-medium">
                  {tool.desc}
                </p>
                
                <div className="mt-6 flex items-center text-brand-400 text-sm font-bold opacity-0 -translate-x-4 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300">
                  Open Tool <svg className="w-4 h-4 ml-1" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* SEO & Content Section */}
      <section className="max-w-5xl mx-auto">
        <div className="bg-slate-900/30 border border-slate-800 rounded-3xl p-8 md:p-16">
          <SectionTitle title="The Science of YouTube Growth" subtitle="Why relying on luck is not a strategy." />
          
          <div className="prose prose-invert prose-lg max-w-none space-y-12">
            {/* Article Part 1 */}
            <div>
              <h3 className="text-2xl font-bold text-brand-300 mb-4">The New Era of Algorithmic Dominance</h3>
              <p className="text-slate-300 leading-relaxed">
                In 2024 and beyond, the YouTube algorithm has evolved from a simple view-counter to a complex neural network prioritizing <strong>Satisfied Watch Time</strong>. It's no longer enough to just get a click; you must deliver on the promise of your thumbnail immediately. This is where TubeMaster differentiates itself. We don't just generate content; we engineer it.
              </p>
              <p className="text-slate-300 leading-relaxed mt-4">
                By leveraging the Gemini 2.5 Flash model, we analyze millions of data points to understand <i>semantic search intent</i>. When you use our Keyword Finder, you aren't just seeing volume numbers—you're seeing the "Difficulty Score" calculated against the current authority of top-ranking channels. This allows small channels to find "Blue Ocean" topics where competition is low, but viewer hunger is high.
              </p>
            </div>

            {/* Article Part 2 */}
            <div className="grid md:grid-cols-2 gap-12 items-center">
              <div>
                <h3 className="text-2xl font-bold text-brand-300 mb-4">Visual Psychology & CTR</h3>
                <p className="text-slate-300 leading-relaxed">
                  The Click-Through Rate (CTR) is the gateway to viral growth. A video with 100% retention will fail if nobody clicks it. Our <strong>Thumbnail Generator</strong> and <strong>Comparator</strong> tools are built on the principles of visual hierarchy and curiosity gaps.
                </p>
                <ul className="mt-4 space-y-2 text-slate-400">
                  <li className="flex items-center gap-2"><span className="text-brand-500">✓</span> Contrast Analysis for mobile screens</li>
                  <li className="flex items-center gap-2"><span className="text-brand-500">✓</span> Emotional facial expression tuning</li>
                  <li className="flex items-center gap-2"><span className="text-brand-500">✓</span> Rule of Thirds composition checks</li>
                </ul>
              </div>
              <div className="bg-slate-950 p-6 rounded-xl border border-slate-800 shadow-inner">
                 <div className="text-center space-y-4">
                    <div className="text-6xl">👁️</div>
                    <h4 className="text-white font-bold text-xl">Did you know?</h4>
                    <p className="text-sm text-slate-400">
                      Thumbnails with a clear "Curiosity Gap"—showing an element that raises a question—have a <strong>58% higher CTR</strong> on average than descriptive thumbnails. Our tools automatically optimize for this.
                    </p>
                 </div>
              </div>
            </div>

            {/* Article Part 3 */}
            <div>
              <h3 className="text-2xl font-bold text-brand-300 mb-4">Retention Engineering: The "Hook" Methodology</h3>
              <p className="text-slate-300 leading-relaxed">
                The first 30 seconds of your video determine its destiny. Our <strong>Script Writer</strong> isn't a generic text generator. It's programmed with the "10-Logic" framework used by the world's top YouTubers.
              </p>
              <p className="text-slate-300 leading-relaxed mt-4">
                It forces a structure that includes a <strong>Pattern Interrupt</strong> every 60-90 seconds. This biological trigger resets the viewer's attention span, preventing the dreaded "drop-off" curve. By pairing audio narration with specific <strong>Visual Cues</strong>, we ensure that your editor knows exactly what B-Roll to use to keep the eyes moving and the brain engaged.
              </p>
            </div>

             {/* Article Part 4 */}
            <div>
               <h3 className="text-2xl font-bold text-brand-300 mb-4">Competitive Intelligence</h3>
               <p className="text-slate-300 leading-relaxed">
                 You don't operate in a vacuum. Our <strong>Competitor Analysis</strong> tool doesn't just tell you what your rivals are doing; it tells you what they are <i>failing</i> to do. By identifying their "Content Gaps"—topics their audience asks for in comments but never gets—you can swoop in and capture their frustrated viewers. This is the fastest way to grow a channel from zero.
               </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="max-w-4xl mx-auto">
        <SectionTitle title="Frequently Asked Questions" center />
        <div className="grid gap-6">
          {faqs.map((faq, i) => (
            <Card key={i} className="hover:border-brand-500/30 transition-colors bg-slate-900/40">
              <h3 className="text-lg font-bold text-white mb-3 flex items-start gap-3">
                <span className="text-brand-500 font-serif italic text-xl">Q.</span>
                {faq.q}
              </h3>
              <p className="text-slate-400 leading-relaxed pl-8">
                {faq.a}
              </p>
            </Card>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-r from-brand-900/20 to-blue-900/20 border border-brand-500/20 rounded-3xl p-12 text-center max-w-5xl mx-auto relative overflow-hidden">
         <div className="absolute top-0 left-0 w-full h-full bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-5"></div>
         <h2 className="text-3xl md:text-5xl font-bold text-white mb-6 relative z-10">Ready to Outsmart the Algorithm?</h2>
         <p className="text-xl text-slate-300 mb-8 max-w-2xl mx-auto relative z-10">Join thousands of creators using TubeMaster to build sustainable, high-income channels.</p>
         <div className="relative z-10 inline-block">
           <Button 
             variant="primary" 
             className="px-10 py-4 text-xl rounded-full shadow-brand-500/50 hover:shadow-brand-500/80 hover:scale-105 transition-transform"
             onClick={() => onNavigate('keywords')}
           >
             Start Creating for Free
           </Button>
         </div>
      </section>
    </div>
  );
};
